spectaql:
  logoFile: sourcegraph-logo.png
  faviconFile: Sourcegraph_Logomark_Color.png

  # Optional string specifying how to build and include CSS for the output:
  #   full: will include a very opinionated set of CSS to make the output look good
  #   basic: will include a very minimal set of CSS mostly used for layout purposes.
  #     You can then season to taste with your own additional CSS
  #
  # Default: full
  cssBuildMode: full # or basic


introspection:
  url: https://sourcegraph.com/.api/graphql


  # Whether to document any Queries at all, in the absence of a metadata directive
  # Default: true
  queriesDocumentedDefault: true
  # Whether to document an individual Query, in the absence of a metadata directive
  # Default: true
  queryDocumentedDefault: true
  # Whether to document a Query Argument, in the absence of a metadata directive
  # Default: true
  queryArgDocumentedDefault: true
  # Hide any Queries with undocumented return types so as not to reference something
  # that seemingly does not exist.
  # Default: true
  hideQueriesWithUndocumentedReturnType: true

  # Whether to document any Mutations at all, in the absence of a metadata directive
  # Default: true
  mutationsDocumentedDefault: true
  # Whether to document an individual Mutation, in the absence of a metadata directive
  # Default: true
  mutationDocumentedDefault: true
  # Whether to document a Mutation Argument, in the absence of a metadata directive
  # Default: true
  mutationArgDocumentedDefault: true
  # Hide any Mutations with undocumented return types so as not to reference something
  # that seemingly does not exist.
  # Default: true
  hideMutationsWithUndocumentedReturnType: true

  # Whether to document any Types at all
  # Default: true
  typesDocumented: true
  # Whether to document an individual Type, in the absence of a metadata directive
  # Default: true
  typeDocumentedDefault: true
  # Whether to document an individual Field, in the absence of a metadata directive
  # Default: true
  fieldDocumentedDefault: true
  # Whether to document an individual Argument, in the absence of a metadata directive
  # Default: true
  argDocumentedDefault: true
  # Hide any fields with undocumented return types so as not to reference something
  # that seemingly does not exist.
  # Default: true
  hideFieldsWithUndocumentedReturnType: true

  #
  #
  ##############################################

servers:
  - url: https://sourcegraph.com/.api/graphql
    description: sourcegraph.com
    production: true

info:
  # Set to true to do no Introduction area rendering at all. Supersedes the below options
  # Default: false
  x-hideIntroduction: false
  # Set to true to not render a friendly Welcome section based on the description in this area
  # Default: false
  x-hideWelcome: false
  # Set to true to not render your intro items
  # Default: false
  x-hideIntroItems: false

  #
  ##############################################

  description: Sourcegraph
  version: 1.0.0
  title: Sourcegraph
  termsOfService: 'https://about.sourcegraph.com/terms'
  contact:
    name: Sourcegraph Support
    email: support@sourcegraph.com
    url: https://about.sourcegraph.com/
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
