on: [push]

jobs:
  spectaql_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: billCaplan/specatql-action@v2
      with:
        who-to-greet: 'Bill C'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"

    - name: Build GraphQL static docs
      run: |
        npx spectaql config.yml
      shell: bash
